enum DOCUMENT_SHELF_COMPONENT_STORE_MODULE_GETTER_TYPE {
    DOCUMENT_GET_ALL = 'documentGetAll',
    LIST_GET_DISPLAY_OPTION = 'listGetDisplayOption',
    LIST_GET_SORT_OPTION_SELECTED = 'listGetSortOptionSelected',
}

export default DOCUMENT_SHELF_COMPONENT_STORE_MODULE_GETTER_TYPE;