enum DOCUMENT_SHELF_COMPONENT_MUTATION_TYPE {
    SET_DOCUMENT_LIST_DISPLAY_OPTION = 'setDocumentListDisplayOption',
    SET_DOCUMENTS = 'setDocuments',
    SET_DOCUMENTS_SORT_OPTION_SELECTED = 'setDocumentSortOptionSelected',
    SORT_DOCUMENTS = 'sortDocuments'
}

export default DOCUMENT_SHELF_COMPONENT_MUTATION_TYPE;