enum DOCUMENT_SHELF_COMPONENT_STORE_MODULE_MUTATION_TYPE {
    DOCUMENT_SET_ALL = 'documentSetAll',
    LIST_DISPLAY_OPTION_SET = 'listDisplayOptionSet',
    LIST_SET_SORT_OPTION_SELECTED = 'listSetSortOptionSelected',
    LIST_SORT = 'listSort'
}

export default DOCUMENT_SHELF_COMPONENT_STORE_MODULE_MUTATION_TYPE;